relative_links:
  enabled: false
baseurl: ""


title: CSCI-UA.0003 Fall 2019, Section 001
email: jversoza at cs dot nyu dot edu

# course
# CSCI-GA.1120-001 - Introduction to Programming - 60 Fifth Ave C10
course_number: "CSCI-UA.0003"
course_section: "001"
course_name: "Introduction to Computer Programming (Limited Prior Experience)"
course_semester: "Fall 2019"
course_dept: DHSS
course_dept_link: http://dhss.nyu.edu/
course_time: "Mondays and Wednesdays, 9:30AM to 10:45AM"
course_room: WWH 201
course_site: https://cs.nyu.edu/courses/fall19/CSCI-UA.0003-001/ 
course_site_alt: http://cs.nyu.edu/~jversoza

office_hours: "<br>Mon/Wed 11:25am - 12:25pm at WWH 422<br>Thurs 12:15pm - 1:15pm at 60 5th Ave"
office_hours_room: WWH 422 on Mon/Wed... Lobby, 60 5th Ave on Thurs

# midterm
midterm1_date: "N/A"
midterm1_time: "N/A"


# finals
final_date: "N/A"
final_time: "N/A"
final_room: "N/A"

resource_prefix: "resources/"
github_username: jversoza
slides_lib: "../../resources/lib"
slides_img_prefix: "../../resources/img"

markdown: kramdown
kramdown:
  entity_output: numeric
  smart_quotes: apos,apos,quot,quot
permalink: none
exclude: [bower_components, README.md, bower.json, gruntfile.js, node_modules]

book1: Python Programming in Context, 2nd Edition
book1_link: http://www.jblearning.com/catalog/9781449699390/
book1_author: Bradley N. Miller, PhD and David L. Ranum, PhD

book2: Python Cookbook
book2_link: http://chimera.labs.oreilly.com/books/1230000000393/index.html
book2_author: David Beazley and Brian K. Jones

